export const projects = [
  {
    name: "explicit magenta",
    description: "program",
    "project-manager": "Fidel Schultz DVM",
    assigned_to: "Ronny Cartwright",
    status: true,
  },
  {
    name: "Consultant Village PCI",
    description: "Chief",
    "project-manager": "Leonel Weissnat III",
    assigned_to: "Monty Greenfelder",
    status: false,
  },
  {
    name: "Road logistical",
    description: "matrix",
    "project-manager": "Wilmer Treutel",
    assigned_to: "Elenor Funk",
    status: false,
  },
  {
    name: "auxiliary plug-and-play navigating",
    description: "Checking Account",
    "project-manager": "Stefanie Jacobson II",
    assigned_to: "Lindsey Zulauf",
    status: true,
  },
  {
    name: "Inlet",
    description: "Pants",
    "project-manager": "Gail Schiller",
    assigned_to: "Kayley Terry",
    status: false,
  },
  {
    name: "Berkshire hack optical",
    description: "Generic Rubber Fish",
    "project-manager": "Ellis Wolff",
    assigned_to: "Mr. Geovanni Heathcote",
    status: false,
  },
  {
    name: "Fantastic SSL",
    description: "Personal Loan Account",
    "project-manager": "Mozell Gusikowski I",
    assigned_to: "Miss Gabriella Powlowski",
    status: false,
  },
  {
    name: "Hat",
    description: "withdrawal",
    "project-manager": "Ferne Homenick",
    assigned_to: "Wyman Rosenbaum",
    status: false,
  },
  {
    name: "auxiliary Liaison Gorgeous Wooden Chips",
    description: "object-oriented",
    "project-manager": "Kendall Emard",
    assigned_to: "Madisyn Bernhard",
    status: true,
  },
  {
    name: "payment website Home Loan Account",
    description: "Rubber",
    "project-manager": "Chandler Klein",
    assigned_to: "Miss Cory Runte",
    status: false,
  },
];
