import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { projects } from "../db";

const Home: NextPage = ({ data }) => {
  console.log(data);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data.map(project=>(
        <h1>{project.name}</h1>
      ))}
    </div>
  );
};

export default Home;


export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      data: projects,
    },
  };
};
